#Se define la version que se esta utilizando del archivo docker-compose
version: app/V1
services:
  #crear la imagen de K8S
  redis-master:
    image: registry.k8s.io/redis:e2e
    ports:
      - "6379"
  #crear la imagen de mysql:5.7    
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    #Se realiza lectura del archivo .env para leer parametros de acceso a BD
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    #Se declara la dependencia que hay de Spring Boot y mysql
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    #Se realiza lectura del archivo .env para leer parametros de acceso a BD y Spring Boot
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    #Se definen los volumenes que se asignaran a la aplicacion asociandolos
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: